server:
  port: 8081

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5433/payment
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true